  0v[m
  develop[m
  frontend[m
  master[m
* [32mpy/feat/diet-init[m
  python[m
  [31mremotes/origin/backend[m
  [31mremotes/origin/be/chore/login[m
  [31mremotes/origin/be/feat/diet[m
  [31mremotes/origin/be/feat/fastApiConnection[m
  [31mremotes/origin/be/feat/mainTodayDiet[m
  [31mremotes/origin/be/feat/refreshToken[m
  [31mremotes/origin/be/feat/serverSocialLogin[m
  [31mremotes/origin/be/fix/auth[m
  [31mremotes/origin/be/fix/child[m
  [31mremotes/origin/be/fix/member[m
  [31mremotes/origin/be/fix/social[m
  [31mremotes/origin/be/fix/swagger[m
  [31mremotes/origin/be/fix/test[m
  [31mremotes/origin/be/refactor/diary[m
  [31mremotes/origin/be/refactor/redis[m
  [31mremotes/origin/be/setting/embeddedRedis[m
  [31mremotes/origin/be/test/basic[m
  [31mremotes/origin/be/test/diary[m
  [31mremotes/origin/be/test/growth[m
  [31mremotes/origin/be/test/main[m
  [31mremotes/origin/be/test/refreshToken[m
  [31mremotes/origin/be/test/swagger[m
  [31mremotes/origin/develop[m
  [31mremotes/origin/fe/feat/auth[m
  [31mremotes/origin/fe/feat/axios[m
  [31mremotes/origin/fe/feat/diary[m
  [31mremotes/origin/fe/feat/diet[m
  [31mremotes/origin/fe/feat/home[m
  [31mremotes/origin/fe/feat/profile[m
  [31mremotes/origin/frontend[m
  [31mremotes/origin/master[m
  [31mremotes/origin/py/feat/diet-init[m
  [31mremotes/origin/py/feat/init-diet[m
  [31mremotes/origin/py/setting/data[m
  [31mremotes/origin/py/setting/data-setting[m
  [31mremotes/origin/py/test/ubcf-test[m
  [31mremotes/origin/python[m
